### ISSUE TITLE
proto 编译新实践

### ISSUE THREAD

**Issue by yangyang5214** [yangyang5214/nil#20]
> 当然本质都是  protoc

###  Taskfile  语法

```
# Taskfile proto 子命令 
  proto:
    desc: build protos
    vars:
      PROTO_FILES: "find .  -type f -name '*.proto'"
    cmds:
      - echo {{.MODULE_NAME}}
      - rm -rf api && mkdir -p api
      - |
        set -ex
        \cp -rf ./protos/* api
        cd ./api && for f in $({{.PROTO_FILES}}); do
            echo $f
            dir_name=$(basename $(dirname $f))
            echo -e "\n" >> $f
            echo "option go_package = \"{{.MODULE_NAME}}/api/$dir_name\";" >> $f
        done

      - cd api && ({{.PROTO_FILES}} | xargs protoc
        --proto_path=.
        --proto_path=./../third_party
        --go_out=paths=source_relative:./
        --go-http_out=paths=source_relative:./
        --go-grpc_out=paths=source_relative:./)
```

### buf 语法

https://buf.build/docs/tutorials/getting-started-with-buf-cli

#### buf.yaml

```
# For details on buf.yaml configuration, visit https://buf.build/docs/configuration/v2/buf-yaml
# buf.build/googleapis/googleapis 按需引入
version: v2
modules:
  - path: ./proto
deps:
  - buf.build/googleapis/googleapis
lint:
  use:
    - STANDARD
breaking:
  use:
    - FILE

```

#### buf.gen.yaml

```
version: v2
clean: true
managed:
  enabled: true
  disable:
    - file_option: go_package
      module: buf.build/googleapis/googleapis
  override:
    - file_option: go_package_prefix
      value: github.com/yangyang5214/mind
plugins:
  - local: protoc-gen-go
    out: ./api
    opt: paths=source_relative
  - local: protoc-gen-go-grpc
    out: ./api
    opt:
      - paths=source_relative
  - local: protoc-gen-go-http
    out: ./api
    opt:
      - paths=source_relative
```

#### 使用

```
# 首次
buf dep update
# 执行protoc
buf generate
```
