### ISSUE TITLE
InStock docker compose

### ISSUE THREAD

**Issue by yangyang5214** [yangyang5214/nil#36]
docker-compose.yaml 

```
services:
  instockdb:
    image: mariadb:lts
    container_name: InStockDbService
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"

  instock:
    image: mayanghua/instock:latest
    container_name: InStock
    depends_on:
      - instockdb
    ports:
      - "9988:9988"
    environment:
      - db_host=InStockDbService
    restart: unless-stopped


networks:
  instock-network:
    driver: bridge
```
